import { schedulingState } from "./approval.js";

const state = { page: "login", user: { name: "演示管理员", role: "ADMIN" }, approvals: [{ userId: "alice", decision: "APPROVE" }], error: "", loading: false };
const pages = { login: "登录", topics: "主题管理", recommendations: "推荐池", task: "任务详情与审批", settings: "数字人/音色设置", metrics: "近 7 天指标" };
const app = document.querySelector("#app");
const guard = (content) => state.loading ? "<p class=notice>正在加载业务 API 数据…</p>" : state.error ? `<p class='notice error'>加载失败：${state.error}</p>` : content;
const nav = () => `<aside><h1>Live Make</h1><p>${state.user.name}<br><small>${state.user.role}</small></p>${Object.entries(pages).map(([id, label]) => `<button class='nav ${state.page === id ? "active" : ""}' data-page='${id}'>${label}</button>`).join("")}</aside>`;
const login = () => `<section><h2>登录</h2><p>使用业务 API 的内部账号登录。</p><label>账号 <input value='admin@example.com'></label><label>密码 <input type=password value='demo'></label><button data-action=login>进入控制台</button><p class=notice>演示模式：后端不可用时仅使用本地样例数据，不连接搜索、LLM、媒体或发布供应商。</p></section>`;
const topics = () => guard(`<section><h2>主题管理</h2><p>管理员可管理启用主题。</p><table><tr><th>主题</th><th>状态</th><th>操作</th></tr><tr><td>AI 生产力</td><td>已启用</td><td><button data-admin>停用</button></td></tr><tr><td>行业热点</td><td>已启用</td><td><button data-admin>编辑</button></td></tr></table><button data-admin>新建主题</button>${state.user.role !== "ADMIN" ? "<p class='notice error'>无权限：仅管理员可管理主题。</p>" : ""}</section>`);
const recommendations = () => guard(`<section><h2>推荐池</h2><p>今日候选选题、来源证据与风险。</p><article><b>AI 助手在客服中的新趋势</b><p>来源：行业报告 / 官方公告 ｜风险：LOW</p><button>选用并创建任务</button><button>重排</button></article><article><b>敏感行业政策解读</b><p>来源：公开政策原文 ｜风险：HIGH</p><button>选用并创建任务</button><button>取消</button></article><p class=notice>空状态：暂无更多推荐时可稍后重排。</p></section>`);
const task = () => { const schedule = schedulingState("HIGH", state.approvals); return guard(`<section><h2>任务详情与审批</h2><p>任务 #LM-20260922-01 ｜状态：SCRIPT_PENDING_APPROVAL ｜风险：HIGH</p><h3>3 份脚本候选</h3><ol><li>效率提升案例（已选）</li><li>趋势观察</li><li>风险提示</li></ol><h3>来源证据、媒体与审计</h3><p>来源：行业报告；媒体产物：等待生成；质检：待执行；发布回执：未发布；审计：Alice 已批准。</p><h3>审批</h3><p>已批准账号：${[...new Set(state.approvals.filter(a => a.decision === "APPROVE").map(a => a.userId))].join("、") || "无"}</p><button data-action=approve>以当前账号批准</button><button data-action=second>模拟第二账号批准</button><button ${schedule.allowed ? "" : "disabled"}>排期发布</button><p class='notice ${schedule.allowed ? "ok" : "error"}'>${schedule.reason}</p><button>失败节点重试</button><button>取消任务</button></section>`); };
const settings = () => guard(`<section><h2>固定数字人/音色设置</h2><p>管理员为账号设置默认形象和音色。</p><label>固定数字人 <select><option>主播小岚</option></select></label><label>固定音色 <select><option>温暖女声</option></select></label><button data-admin>保存设置</button>${state.user.role !== "ADMIN" ? "<p class='notice error'>无权限：仅管理员可修改固定设置。</p>" : ""}</section>`);
const metrics = () => guard(`<section><h2>最近 7 天核心指标</h2><div class=cards><article><b>已发布</b><strong>18</strong></article><article><b>通过率</b><strong>82%</strong></article><article><b>平均处理时长</b><strong>26 分钟</strong></article><article><b>失败任务</b><strong>2</strong></article></div><p>按日趋势：周一 2 · 周二 3 · 周三 1 · 周四 4 · 周五 3 · 周六 2 · 周日 3</p></section>`);
const content = () => ({ login, topics, recommendations, task, settings, metrics })[state.page]();
function render() { app.innerHTML = `<main>${nav()}<div class=content>${content()}</div></main>`; app.querySelectorAll("[data-page]").forEach((button) => button.onclick = () => { state.page = button.dataset.page; render(); }); app.querySelector("[data-action=login]")?.addEventListener("click", () => { state.page = "topics"; render(); }); app.querySelector("[data-action=approve]")?.addEventListener("click", () => { state.approvals.push({ userId: "admin", decision: "APPROVE" }); render(); }); app.querySelector("[data-action=second]")?.addEventListener("click", () => { state.approvals.push({ userId: "bob", decision: "APPROVE" }); render(); }); }
render();
