import { schedulingState } from "./approval.js";
import { createApi } from "./api.js";

const api = createApi();
const state = { page: "login", user: { name: "演示管理员", role: "ADMIN" }, approvals: [{ userId: "alice", decision: "APPROVE" }], error: "", loading: false, topics: [], recommendations: [], metrics: {}, taskData: {}, dataSource: "demo" };
const pages = { login: "登录", topics: "主题管理", recommendations: "推荐池", task: "任务详情与审批", settings: "数字人/音色设置", metrics: "近 7 天指标" };
const app = document.querySelector("#app");
const guard = (content) => state.loading ? "<p class=notice>正在加载业务 API 数据…</p>" : state.error ? `<p class='notice error'>加载失败：${state.error}</p>` : content;
const nav = () => `<aside><h1>Live Make</h1><p>${state.user.name}<br><small>${state.user.role}</small></p>${Object.entries(pages).map(([id, label]) => `<button class='nav ${state.page === id ? "active" : ""}' data-page='${id}'>${label}</button>`).join("")}</aside>`;
const login = () => `<section><h2>登录</h2><p>使用业务 API 的内部账号登录。</p><label>账号 <input value='admin@example.com'></label><label>密码 <input type=password value='demo'></label><button data-action=login>进入控制台</button><p class=notice>演示模式：后端不可用时仅使用本地样例数据，不连接搜索、LLM、媒体或发布供应商。</p></section>`;
const topics = () => guard(`<section><h2>主题管理</h2><p>管理员可管理启用主题。数据来源：${state.dataSource === "api" ? "业务 API" : "演示数据（业务 API 不可用）"}</p><table><tr><th>主题</th><th>状态</th><th>操作</th></tr>${state.topics.length ? state.topics.map(topic => `<tr><td>${topic.name}</td><td>${topic.enabled ? "已启用" : "已停用"}</td><td><button data-admin>编辑</button></td></tr>`).join("") : "<tr><td colspan=3>暂无主题</td></tr>"}</table><button data-admin>新建主题</button>${state.user.role !== "ADMIN" ? "<p class='notice error'>无权限：仅管理员可管理主题。</p>" : ""}</section>`);
const recommendations = () => guard(`<section><h2>推荐池</h2><p>今日候选选题、来源证据与风险。数据来源：${state.dataSource === "api" ? "业务 API" : "演示数据"}</p>${state.recommendations.length ? state.recommendations.map(item => `<article><b>${item.title}</b><p>来源：${item.source} ｜风险：${item.risk}</p><button>选用并创建任务</button><button>${item.risk === "HIGH" ? "取消" : "重排"}</button></article>`).join("") : "<p class=notice>暂无推荐。</p>"}</section>`);
const task = () => { const data = state.taskData; const schedule = schedulingState(data.risk || "HIGH", state.approvals); return guard(`<section><h2>任务详情与审批</h2><p>任务 #${data.id || "LM-20260922-01"} ｜状态：${data.status || "加载中"} ｜风险：${data.risk || "HIGH"}</p><h3>3 份脚本候选</h3><ol>${(data.scripts || []).map(script => `<li>${script}</li>`).join("")}</ol><h3>来源证据、媒体与审计</h3><p>来源：${data.evidence || "—"}；媒体产物：${data.media || "—"}；质检：${data.quality || "—"}；发布回执：${data.receipt || "—"}；审计：Alice 已批准。</p><h3>审批</h3><p>已批准账号：${[...new Set(state.approvals.filter(a => a.decision === "APPROVE").map(a => a.userId))].join("、") || "无"}</p><button data-action=approve>以当前账号批准</button><button data-action=second>模拟第二账号批准</button><button ${schedule.allowed ? "" : "disabled"}>排期发布</button><p class='notice ${schedule.allowed ? "ok" : "error"}'>${schedule.reason}</p><button>失败节点重试</button><button>取消任务</button></section>`); };
const settings = () => guard(`<section><h2>固定数字人/音色设置</h2><p>管理员为账号设置默认形象和音色。</p><label>固定数字人 <select><option>主播小岚</option></select></label><label>固定音色 <select><option>温暖女声</option></select></label><button data-admin>保存设置</button>${state.user.role !== "ADMIN" ? "<p class='notice error'>无权限：仅管理员可修改固定设置。</p>" : ""}</section>`);
const metrics = () => guard(`<section><h2>最近 7 天核心指标</h2><p>数据来源：${state.dataSource === "api" ? "业务 API" : "演示数据"}</p><div class=cards><article><b>已发布</b><strong>${state.metrics.published ?? "—"}</strong></article><article><b>通过率</b><strong>${state.metrics.passRate ?? "—"}</strong></article><article><b>平均处理时长</b><strong>${state.metrics.duration ?? "—"}</strong></article><article><b>失败任务</b><strong>${state.metrics.failed ?? "—"}</strong></article></div><p>按日趋势：周一 2 · 周二 3 · 周三 1 · 周四 4 · 周五 3 · 周六 2 · 周日 3</p></section>`);
const content = () => ({ login, topics, recommendations, task, settings, metrics })[state.page]();
async function load(page) { state.loading = true; render(); const result = page === "topics" ? await api.getTopics() : page === "recommendations" ? await api.getRecommendations() : page === "metrics" ? await api.getMetrics() : await api.getTask("LM-20260922-01"); if (page === "topics") state.topics = Array.isArray(result.data) ? result.data : []; if (page === "recommendations") state.recommendations = Array.isArray(result.data) ? result.data : []; if (page === "metrics") state.metrics = result.data || {}; if (page === "task") state.taskData = result.data || {}; state.dataSource = result.source; state.loading = false; render(); }
function render() { app.innerHTML = `<main>${nav()}<div class=content>${content()}</div></main>`; app.querySelectorAll("[data-page]").forEach((button) => button.onclick = () => { state.page = button.dataset.page; render(); if (["topics", "recommendations", "metrics", "task"].includes(state.page)) load(state.page); }); app.querySelector("[data-action=login]")?.addEventListener("click", () => { state.page = "topics"; load("topics"); }); app.querySelector("[data-action=approve]")?.addEventListener("click", () => { state.approvals.push({ userId: "admin", decision: "APPROVE" }); render(); }); app.querySelector("[data-action=second]")?.addEventListener("click", () => { state.approvals.push({ userId: "bob", decision: "APPROVE" }); render(); }); }
render();
